### PR TITLE
Easier includes of the library

### PR DESCRIPTION
**Pull request by DataTables**
Previously you would need to include each of the files from this repo
individually in the script(s) that actually use the files. While easy
enough to do, it would be easier to simply include a single base file
and have it perform the required includes for us.

I've added this as a separate file rather than into Client.php to
preserve backwards compatibility. New users can include KM.php while the
folks including the files individually can ignore the new file and carry
on with the old way.

### CODE REVIEW

**Comment by Gargron** [comment]
It's been forever since I made this but if I remember correctly you don't need to require anything manually, you can use autoloading, and I do believe that if you use Composer you get autoloading for free.

**Comment by DataTables** [comment]
That's a point - I'm not using Composer so I'm not sure what the impact of this will be on Composer.

It is possible to create a custom auto loader using [spl_autoload_register](http://php.net/manual/en/function.spl-autoload-register.php) but it seems fairly redundant for just a couple of files like this where it is easy to specify the includes specifically. At the moment, if you aren't using Composer, then you need to include the files manually (at least I did :-) ).

**Comment by eskfung** [comment]
@bhardin is this PR something you'd be able to review?

**Comment by bhardin** [comment]
I would be fine with this. However, my PHP is rusty. @percyhanna Can you take a look at this?

**Comment by percyhanna** [comment]
Should work fine with Composer as it uses `require_once` to avoid loading any files multiple times.

**Pull request merged**
